#Séries Temporais
###Análise e manipulação de dados temporais com Python e Pandas.

*Mariana de Souza Gomes*

##O que são séries temporais?
Uma série temporal é um conjunto de observações coletadas ao longo de um determinado tempo, sendo o tempo um fator fundamental, pois a ordem em que os dados são observados pode influenciar a análise.

###Exemplos


*   Temperatura registrada ao longo dos dias
*   Vendas de uma empresa ao longo dos meses
*   Inflação ao longo dos anos

As observações podem ocorrer em intervalos regulares ou irregulares

In [ ]:
import pandas as pd

dados = {
    "Data": ["01/08/2026", "02/08/2026", "03/08/2026", "04/08/2026", "05/08/2026"],
    "Vendas": [120, 135, 90, 128, 163]
}

df = pd.DataFrame(dados)

df

         Data  Vendas
0  01/08/2026     120
1  02/08/2026     135
2  03/08/2026      90
3  04/08/2026     128
4  05/08/2026     163



Nesse exemplo, cada observação possui uma data e um número de vendas. A variável **Data** representa o tempo, enquanto **Vendas** representa o valor observado.
Como as vendas estão sendo acompanhadas ao longo do tempo, temos uma série temporal.

##Representação do Tempo

Os dados de uma série temporal podem representar o tempo de diferentes maneiras.

###Timestamp
Representa um instante específico no tempo.
**Exemplo:** 19/08/2026 às 17:38:00

###Período Fixo
Representa um período completo
**Exemplo:** Agosto de 2026

###Intervalo de Tempo
Representa um período definido por um início e um fim
**Exemplo:** de 01/08/2026 às 12:00 até 01/09/2026 às 12:00

###Tempo Decorrido
Representa o tempo passado desde o início de um evento ou experimento
**Exemplo:** Medir a temperatura de um forno a cada 10 segundos após o acionamento.

##Datetime e Timedelta

O python possui ferramentas próprias para trabalhar com datas, horários e intervalos de tempo.

### datetime
Representa uma data e um horário específicos.

### timedelta
Representa uma diferença ou duração de tempo.

Podemos utilizar essas ferramentas para realizar operações com datas, como calcular diferenças ou adicionar e remover períodos.

In [ ]:
from datetime import datetime, timedelta

data = datetime(2026, 8, 19, 17, 52)

data

datetime.datetime(2026, 8, 19, 17, 52)

In [ ]:
intervalo = timedelta(days=4)

nova_data = data + intervalo

nova_data

datetime.datetime(2026, 8, 23, 17, 52)

In [ ]:
data_inicial = datetime(2026, 8, 19)
data_final = datetime(2026, 8, 28)

diferenca = data_final - data_inicial

diferenca

datetime.timedelta(days=9)

Resumidamente:
- 'datetime' representa **quando** algo aconteceu
- 'timedelta' representa **quanto tempo** passou

Ambas são ferramentas base para trabalhar com datas antes de utilizar as ferramentas específicas do Pandas.

##Datas no Pandas

O pandas possui ferramentas específicas para trabalhar com conjuntos de datas.

Uma das principais é a função 'pd.to_datetime()', que converte diferentes representações de datas para um formato que o Pandas consegue manipular.

Isso facilita operações como:


*   ordenar datas
*   selecionar períodos
*   calcular diferenças
*   criar índices temporais

In [ ]:
import pandas as pd

datas = ["19/08/2026", "20/08/2026", "21/08/2026"]

datas_convertidas = pd.to_datetime(
    datas,
    format="%d/%m/%Y"
    )

datas_convertidas

DatetimeIndex(['2026-08-19', '2026-08-20', '2026-08-21'], dtype='datetime64[ns]', freq=None)

Valores ausentes: NaT

Assim como o Pandas utiliza "NaN" para representar valores numéricos ausentes, ele utiliza "NaT" (*Not a Time*) para representar uma data ou horário ausente.

In [ ]:
datas = ["19/08/2026", None, "21/08/2026"]

datas_convertidas = pd.to_datetime(
    datas,
    format="%d/%m/%Y"
    )

datas_convertidas

DatetimeIndex(['2026-08-19', 'NaT', '2026-08-21'], dtype='datetime64[ns]', freq=None)

Ao converter as datas para um formato reconhecido pelo Pandas, podemos utilizar recursos específicos para análise de séries temporais.

##DatetimeIndex

O "DatetimeIndex" é um índice de Pandas formado por datas e horários. Ao utilizar datas como índice de uma "Series" ou de um "DataFrame", o Pandas consegue reconhecer que os dados estão organizados temporalmente.

Isso permite realizar operações específicas com datas, como:


*   selecionar um determinado dia
*   selecionar um mês ou ano
*   filtrar intervalos de tempo
*   organizar e analisar os dados cronologicamente

In [ ]:
datas = pd.to_datetime([
    "2026-08-01",
    "2026-08-02",
    "2026-08-03",
    "2026-08-04",
    "2026-08-05"
])

vendas = [120, 135, 90, 128, 163]

serie = pd.Series(vendas, index=datas)

serie

2026-08-01    120
2026-08-02    135
2026-08-03     90
2026-08-04    128
2026-08-05    163
dtype: int64

In [ ]:
serie.index

DatetimeIndex(['2026-08-01', '2026-08-02', '2026-08-03', '2026-08-04',
               '2026-08-05'],
              dtype='datetime64[ns]', freq=None)

Como nossas datas estão no índice, podemos utilizar as próprias datas para selecionar os dados.

In [ ]:
serie["2026-08-03"]

np.int64(90)

In [ ]:
serie["2026-08-02":"2026-08-04"]

2026-08-02    135
2026-08-03     90
2026-08-04    128
dtype: int64

Em resumo

O 'DatetimeIndex' permite que o Pandas trate as datas como parte fundamental dos dados. Com ele, podemos consultar e filtrar informações utilizando diretamente períodos de tempo.

##Criando uma Série Temporal

O Pandas possui a função 'pd.date_range' para gerar automaticamente uma sequência de datas.

Ela é útil quando as observações possuem uma frequência definida, como:


*   diariamente
*   semanalmente
*   mensalmente
*   anualmente

In [ ]:
datas = pd.date_range(
    start="2026-01-01",
    periods=12,
    freq="ME"
)

datas

DatetimeIndex(['2026-01-31', '2026-02-28', '2026-03-31', '2026-04-30',
               '2026-05-31', '2026-06-30', '2026-07-31', '2026-08-31',
               '2026-09-30', '2026-10-31', '2026-11-30', '2026-12-31'],
              dtype='datetime64[ns]', freq='ME')

Agora podemos associar um valor a cada uma das datas geradas.

In [ ]:
vendas = [120, 135, 90, 130, 200, 97, 150, 139, 187, 210, 180, 100]

serie_vendas = pd.Series(
    vendas,
    index=datas
)

serie_vendas

2026-01-31    120
2026-02-28    135
2026-03-31     90
2026-04-30    130
2026-05-31    200
2026-06-30     97
2026-07-31    150
2026-08-31    139
2026-09-30    187
2026-10-31    210
2026-11-30    180
2026-12-31    100
Freq: ME, dtype: int64

A frequência define de quanto em quanto tempo as observações acontecem.

In [ ]:
datas_diarias = pd.date_range(
    start="2026-01-01",
    periods=5,
    freq="D"
)

datas_diarias

DatetimeIndex(['2026-01-01', '2026-01-02', '2026-01-03', '2026-01-04',
               '2026-01-05'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
datas_semanais = pd.date_range(
    start="2026-01-01",
    periods=5,
    freq="W"
)

datas_semanais

DatetimeIndex(['2026-01-04', '2026-01-11', '2026-01-18', '2026-01-25',
               '2026-02-01'],
              dtype='datetime64[ns]', freq='W-SUN')

Em resumo

A função 'pd.date_range()' permite criar sequências de datas de forma automática. O parâmetro 'freq' define a frequência das observações, tornando a criação de séries temporais mais prática.

#Manipulando uma Série Temporal

Quando as datas são utilizadas como índice, podemos selecionar facilmente:


*   uma data específica
*   um mês ou ano
*   um intervalo de tempo

Isso facilita a análise de diferentes períodos da série.

In [ ]:
serie_vendas["2026-03":"2026-06"]

2026-03-31    128
2026-04-30    150
2026-05-31    162
2026-06-30    170
Freq: ME, dtype: int64

In [ ]:
serie_vendas["2026"]

2026-01-31    120
2026-02-28    135
2026-03-31    128
2026-04-30    150
2026-05-31    162
2026-06-30    170
2026-07-31    165
2026-08-31    180
2026-09-30    190
2026-10-31    185
2026-11-30    200
2026-12-31    215
Freq: ME, dtype: int64

Além de selecionar períodos, podemos aplicar operações estatísticas aos valores da série como, por exemplo, calcular a média das vendas e descobrir o maior e menor valor.

In [ ]:
media_vendas = serie_vendas.mean()

media_vendas

np.float64(166.66666666666666)

In [ ]:
print("Maior valor:", serie_vendas.max())
print("Menor valor:", serie_vendas.min())

Maior valor: 215
Menor valor: 120

O Pandas permite selecionar períodos e aplicar operações estatísticas aos dados.

Dessa forma, podemos identificar valores máximos e mínimos, calcular médias e analisar o comportamento dos dados ao longo do tempo.

##Exemplo Prático

Vamos analisar as vendas mensais de uma loja durante o ano de 2026. Nesse exemplo, vamos:


*   Criar uma sequência de datas
*   Associar valores às datas
*   Criar uma série temporal
*   Selecionar um período
*   Realizar uma análise simples dos dados

In [ ]:
datas = pd.date_range(
    start="2026-01-01",
    periods=12,
    freq="ME"
)

datas

DatetimeIndex(['2026-01-31', '2026-02-28', '2026-03-31', '2026-04-30',
               '2026-05-31', '2026-06-30', '2026-07-31', '2026-08-31',
               '2026-09-30', '2026-10-31', '2026-11-30', '2026-12-31'],
              dtype='datetime64[ns]', freq='ME')

In [ ]:
vendas = [120, 135, 128, 150, 162, 170, 165, 180, 190, 185, 200, 215]

vendas

[120, 135, 128, 150, 162, 170, 165, 180, 190, 185, 200, 215]

In [ ]:
serie_vendas = pd.Series(
    vendas,
    index=datas
)

serie_vendas

2026-01-31    120
2026-02-28    135
2026-03-31    128
2026-04-30    150
2026-05-31    162
2026-06-30    170
2026-07-31    165
2026-08-31    180
2026-09-30    190
2026-10-31    185
2026-11-30    200
2026-12-31    215
Freq: ME, dtype: int64

Analisando um período

Podemos selecionar apenas os meses que queremos analisar utilizando as próprias datas.

In [ ]:
periodo = serie_vendas["2026-03":"2026-06"]

periodo

2026-03-31    128
2026-04-30    150
2026-05-31    162
2026-06-30    170
Freq: ME, dtype: int64

In [ ]:
print("Média das vendas:", periodo.mean())
print("Maior número de vendas:", periodo.max())
print("Menor número de vendas:", periodo.min())

Média das vendas: 152.5
Maior número de vendas: 170
Menor número de vendas: 128